### ISSUE TITLE
Basic Landing/Splash page

### ISSUE THREAD

**Issue by alexdovzhanyn** [ElixiumNetwork/elixium_core#14]
It would be nice to have a basic landing page where we can showcase the idea and maybe allow people to join a mailing list regarding development.

**Comment by Zac-Garby** [comment]
I'd be interested in doing this, if nobody else wants to. Would it be hosted on GitHub pages?

**Comment by alexdovzhanyn** [comment]
I think we're looking at having an actual self hosted site. Im meeting with a designer later today to see if we can agree on a design, and then I'll attach it to this issue

**Comment by ajmalhassan** [comment]
I'd be interested in doing this too

**Comment by alexdovzhanyn** [comment]
Talked to the designer, we're awaiting one other designer to finish the logo/branding and then passing that off to the web designer who'll make something that looks great. I'm expecting to have a design by the end of next week

**Comment by TacticalGoat** [comment]
I'm down for this too.

**Comment by ajmalhassan** [comment]
@alexdovzhanyn , any updates?

**Comment by Zac-Garby** [comment]
@ajmalhassan Two designs were posted on the discord: ![](https://cdn.discordapp.com/attachments/417761501642883076/418258572355436553/UltraDark_Above_the_Fold_V1.png) and ![](https://cdn.discordapp.com/attachments/417761501642883076/418258576558129163/UltraDark_Above_the_Fold_V5.png)

**Comment by alexdovzhanyn** [comment]
@ajmalhassan @Zac-Garby neither of which are the final versions. We're close, but not quite ready to start the website

**Comment by ajmalhassan** [comment]
@alexdovzhanyn , play with black a lot more, if done right it'll match the name and more importantly it'll look amazing!

**Comment by alexdovzhanyn** [comment]
Finalized design: http://zpl.io/bAGyZJp

**Comment by alexdovzhanyn** [comment]
https://elixium.app
