### ISSUE TITLE
Research Solidity vs Javascript for contracting

### ISSUE THREAD

**Issue by alexdovzhanyn** [ElixiumNetwork/elixium_core#17]
We should use either Solidity or Javascript for the contracting language. Let's do some research on which one would fit better for the project. Here are some general pros and cons of each:

### Javascript
**Pros:**
* Used by many people (currently the most used language in the world)
* There is a javascript engine library already existing in erlang

**Cons:**
* Because javascript is turing complete, there is a possibility of having contracts with infinite loops, which we'd have to figure out how to handle

### Solidity
**Pros:**
* Solidity was built for the exact purpose of creating contracts

**Cons:**
* May not be as flexible as we want it to be
* May be harder to implement into elixir

**Comment by alexdovzhanyn** [comment]
#15

**Comment by Nijinsha** [comment]
I think keeping smart contracts on their own side chains would be better. So that smart contracts won't affect main chain size.

**Comment by alexdovzhanyn** [comment]
I'm not sure how that would change anything though, since every full node/miner would need to store the side chains anyway, right? Would that also mean that you would need a separate transaction pool just for contracts? And seperate blocks for them as well, if theyre being stored on a seperate side chain?

**Comment by Nijinsha** [comment]
I think they have separate blocks

**Comment by Nijinsha** [comment]
I haven't looked at the details but I think neo or nem use side chains.

**Comment by alexdovzhanyn** [comment]
It might be worth looking into, im not sure how they do it but I think neo is PoS, which might lend itself better to having side chains. Im having difficulty imagining how a side chain would work in PoW, since miners would essentially need to choose whether to mine transaction blocks or contract blocks

**Comment by Zac-Garby** [comment]
With JavaScript, I don’t think the infinite loop problem is solvable without having some kind of timeout

**Comment by alexdovzhanyn** [comment]
Yeah I agree, I saw something that codepen and repl use thats called loop-protect, but nijinsha shared the way that ethereum handles it with gas and I think that might be the way to go

**Comment by antoninadert** [comment]
If you want turing-complete (we should) then infinite loops are a problem. 
This has been solved with ETH and NEO by making people pay for computation (GAS).

For the sidechain solution I don't know the details, but I know some famous blockchain that do this: ARDOR, ARK, LISK, ASCH

It may be worth having a look

**Comment by alexdovzhanyn** [comment]
Im leaning towards using javascript and just having some sort of abstract syntax tree to parse the script before we run it, and assign costs to each operation similar to how ethereum does, but I'll take a look at how some of the side chains work as well

**Comment by irthos** [comment]
This is a dated example, but JS/Erlang interop could be worth considering to bridge the divide.

**Comment by antoninadert** [comment]
If you were to ask me now: I believe solidity is the go-to language for many developers and this would be smart to be compatible and be able to reuse a solidity code.

That being said javascript is very user friendly and if you manage to get something smarter than solidity, this could be a very good option 1 for elixium. 

It all depends on simplicity and tooling in the end. You will have more traction if you support solidity though

**Comment by alexdovzhanyn** [comment]
We'll be using javascript compiled to WASM

**Comment by zac-garby** [comment]
Does that mean that any other language that compiles to WASM will be supported too? If so, awesome

**Comment by Nijinsha** [comment]
possible
