### ISSUE TITLE
A GUI App

### ISSUE THREAD

**Issue by zac-garby** [ElixiumNetwork/elixium_core#26]
For now, this wouldn't be very useful. Once we have issues #24, #20, and #10 closed and have wallets and the network and all that implemented, it'd be nice to have a GUI app for mining, making transactions, contracts, etc...

I'm not sure if this would be best done as a web-app (communicating with UltraDark via web sockets) or as a native GUI.

**Comment by alexdovzhanyn** [comment]
Interesting idea :) I think this would work pretty well for a wallet where you can create transactions, but a gui for mining wouldnt be practical cause it slows down the speed of hashing, so no one would use it, but it would probably be a good idea to have a native app to use as a wallet, and a javascript library for web that allows interaction with the blockchain and the contracts on it

**Comment by Zac-Garby** [comment]
I don’t think it would slow down mining, because it’d only need to mine in a separate process and update the UI when a new block is mined

**Comment by alexdovzhanyn** [comment]
The only thing with that is, as we're currently built, it requires a cpu to mine ultradark, as there isnt a very easy way to mine sha3 on gpu, so any thread we use for gui graphics processing is a thread that isnt being used to mine

**Comment by alexdovzhanyn** [comment]
Also what would be the major advantages of having a gui miner vs cli? theyre both only there to show you the status, since theyre not interactive

**Comment by Nijinsha** [comment]
I don't think there is a need for miner App Since most of the miners I have doesn't even have a monitor. Most of coins onlu have cli tool ( I think monero has miner builtin to the wallet). I think a wallet is necessary if you want people to use it either native or a webapp(or like mist)  that connects with the  local node's port.

**Comment by fantypants** [comment]
Well, there's a few reasons a gui app is a good step IMO. You can start to appeal to the less tech-centric crowd that doesn't know CLI, thus getting a larger audience base and you also start to promote a bit more creativity from people (crypto investors and the sort love all there own graphs) could make it a sandbox type development

**Comment by alexdovzhanyn** [comment]
I still dont understand why this would be necessary. It would show you all the same exact things that the terminal would show, except in a slightly more user-friendly fashion. I'm all for having a gui wallet, but having a gui mining application doesnt make any sense. The user wouldnt need to open a terminal and run a command to mine, the finalized version of the miner would just be a shell script that the user needs to double click, which would open the terminal for them and start mining

**Comment by fantypants** [comment]
Yeah that's true for technical people, but for overall market adoption and early appeal having a gui based system appeals to the crowd that aren't comfortable just double clicking a shell script, they like to have pretty and nice things with buttons they can click haha

**Comment by alexdovzhanyn** [comment]
Sure, but what buttons would they click on a miner? Its either on or off, and the only thing it does is display text whenever youve mined a new block

**Comment by fantypants** [comment]
Yep, we built one using C#/WPF for a desktop client, all it did was start mining with a button and then stop when they clicked stop, just showed them how much they've mined basically. Seems stupid, but it tested our theory for market adoption.

**Comment by alexdovzhanyn** [comment]
I guess that might not be so bad. Its possible that maybe making a phone app that lets them mine would be a good idea, as people would easily be able to contribute to the mining ecosystem in any small way they could. If someone wants to make a gui miner, im interested to see how much better non-technical people would react to it vs using a shell

**Comment by fantypants** [comment]
Phone app wouldn't be too bad, I would be curious to see how the snapdragons can mine. But I could port the shell script into the existing gui WPF framework if needed? would need API's available for mined balance etc

**Comment by alexdovzhanyn** [comment]
What form would the api need to be in?

**Comment by fantypants** [comment]
REST API with Token based authentication

**Comment by alexdovzhanyn** [comment]
Why would you need a rest api to interact with a program running locally?

**Comment by fantypants** [comment]
ahh, I had to have workarounds for this, but it was to do with payment auth through it, scratch the REST API, any web service api will do, format doesn't matter as It'll parse any type

**Comment by Zac-Garby** [comment]
The phone app could maybe be used to tell a computer to start/stop mining, because I don't think phone processors would be that good at mining.

**Comment by Zac-Garby** [comment]
This all sounds quite fun. Was the decision to do desktop app web-based or an actual app? I've heard Elixir isn't very good for making actual apps.

**Comment by alexdovzhanyn** [comment]
I dont think we need any web based api for an app that runs locally. Theres no need to route a request through an rntire network in order to mine. I think we'd want to do native, maybe not necessarily in elixir. 

I think its important that we realize this as a nice-to-have, and it should probably be done further into the future when we have a more stable blockchain

**Comment by fantypants** [comment]
The API is for getting how much they've mined, not the mining itself, the client would be built in C#/Java or something (mine was in C#) but it introduces interactivity from the non-technical crowd, and increases the market adoption.

**Comment by alexdovzhanyn** [comment]
@mbenatti Im still skeptical over how useful it would be to have a Gui miner application, but I think scenic would be a very good way to make a wallet interface

**Comment by fantypants** [comment]
Can conclude this is basically solved ;)
