### ISSUE TITLE
Modifying the outputs of a transaction doesnt invalidate it

### ISSUE THREAD

**Issue by alexdovzhanyn** [ElixiumNetwork/elixium_core#40]
When a transaction is created, the inputs are all signed with the signature of the keyholder. The outputs of the transaction are not signed, and therefore are interchangeable. For example:

1. Bob wants to send Mary 2 shades.
2. Bob creates a transaction and signs all the inputs to the transaction.
3 .Bob specifies the outputs of the transaction, pointing them to Mary's UltraDark address
4. Bob sends his transaction to the UltraDark network.
5. Gary, a bad actor on the network, upon receiving the transaction, decides to swap the outputs from pointing to Mary's address to instead point to his address.
6. Gary forwards this new forged version of the transaction to the network, and he steals the shades, even though the inputs were signed by Bob
7. Don't be Gary, nobody likes Gary

As we can see, because we don't sign the outputs of the transaction, there is no way of telling that the outputs have not been forged with. Solving this is not as simple as just signing the outputs, because the inputs can be signed by any number of keys owned by the creator of the transaction. If we sign all the outputs using just one of the keys, this fails validation because that one key will not necessarily be attached to all the UTXOs that are in the inputs. 

How can we solve this in a way that allows transactions to have multiple inputs, spanning accross multiple keys?

**Comment by alexdovzhanyn** [comment]
The proposed solution is to have each key from the inputs sign the outputs. There are 2 ways we can go about this (which may or may not work):

1. Have `x = sign(key1, data)`, then `x = sign(key2, x)`, then `x = sign(key3, x)`, and so on, until each key has signed.
2. Extend the utxo to have a signature for each key, e.g:
```elixir
%{
  addr: "some address", 
  txoid: "something", 
  signature_1: "blah", 
  signature_2: "blahblah", 
  signature_3: "whatever"
  ...
}
```

**Comment by alexdovzhanyn** [comment]
Or just include the merkle root of the outputs in the transaction id, which is probably a _much_ better solution

**Comment by hlongvu** [comment]
The transaction hash is currently the hash of all inputs id.
```
  @spec calculate_hash(Transaction) :: String.t()
  def calculate_hash(transaction) do
    transaction.inputs
    |> Enum.map(& &1.txoid)
    |> Utilities.calculate_merkle_root()
  end
```
I think it is not enough. We should hash all the things in transaction (except id) then use this hash as the transaction id. 
This will prevent anything inside a transaction to be forged.
As in bitcoin: https://bitcoin.stackexchange.com/a/2233

**Comment by alexdovzhanyn** [comment]
Good point, we can create a hash representation of each utxo by concatting its txoid, amount, from, and to fields, then hashing that value. We can then find the merkle root of those hashes and use them as the transaction id

**Comment by alexdovzhanyn** [comment]
After looking into it some more, it looks like we'll need to implement a sigscript onto the transactions -- otherwise we wont be able to have both single sig and multisig transactions within the same model.
