### ISSUE TITLE
Make Genesis block a mined block

### ISSUE THREAD

**Issue by alexdovzhanyn** [ElixiumNetwork/elixium_core#64]
The genesis block is currently hard-coded into the codebase. Let's change this so that the genesis block is mined just like all the other blocks, but allow it to be a special case so that it doesn't need to have a `previous_hash`.

**Comment by alexdovzhanyn** [comment]
@chaintip

**Comment by alexdovzhanyn** [comment]
@chaintip 30 days

**Comment by chaintip** [comment]
`0.00906372 BCH`| `~   5.05 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4sncy2y8dwl5kqe2ql0u7saf6k8sfgm04qya) to this issue by @alexdovzhanyn.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/48), get a pull request merged with ```@chaintip fixes #64``` in the creation comment.

**Comment by alexdovzhanyn** [comment]
Fixed in #65
